### ISSUE TITLE
[mbcompact] error : <MBTiles> has no method '_insert'

### ISSUE THREAD

**Issue by alarribeau** [mapbox/node-mbtiles#15]
Hello,

First I must say, that I am a total noob regarding node or js so my problem may be stupid. Here it is :

I have installed node-mbtiles (branch node-v6) and I have the following error when using the mbcompact tool :

```
-------------------------------------------------- TRACE -----------------------------
> ./mbcompact test.mbtiles

The "sys" module is now called "util". It should have a similar interface.
00 -------------- 50 -------------- 100

/home/ubuntu/src/node-mbtiles/node_modules/step/lib/step.js:39
        throw arguments[0];
                       ^
TypeError: Object #<MBTiles> has no method '_insert'
    at Function.<anonymous> (/home/ubuntu/src/node-mbtiles/bin/mbcompact:95:37)
    at next (/home/ubuntu/src/node-mbtiles/node_modules/step/lib/step.js:51:23)
    at Step (/home/ubuntu/src/node-mbtiles/node_modules/step/lib/step.js:122:3)
    at Statement.<anonymous> (/home/ubuntu/src/node-mbtiles/bin/mbcompact:93:21)
--------------------------------------------------
```

Can you help me please ?

Thanks!
Alex

**Comment by mapsam** [comment]
Hi y'all, the bin commands were removed in 0.3.0 https://github.com/mapbox/node-mbtiles/commit/a98037dbdfd19f6cf5a72737cf338654686f734e so going to close this.
