### ISSUE TITLE
mbcheck Metadata: Cannot call method 'toString' of null

### ISSUE THREAD

**Issue by shr3k** [mapbox/node-mbtiles#22]
Hi, I'm getting this kind of error with mbtiles file generated by tilemill:

root@swamp:/mnt/tmp# mbcheck vys_myto_m_volby.mbtiles
Metadata

/usr/lib/node_modules/mbtiles/node_modules/step/lib/step.js:39
        throw arguments[0];
                       ^
TypeError: Cannot call method 'toString' of null
    at /usr/lib/node_modules/mbtiles/lib/utils.js:10:29
    at Array.map (native)
    at /usr/lib/node_modules/mbtiles/lib/utils.js:8:44
    at Array.map (native)
    at Object.utils.table (/usr/lib/node_modules/mbtiles/lib/utils.js:7:29)
    at Function.<anonymous> (/usr/lib/node_modules/mbtiles/bin/mbcheck:52:15)
    at next (/usr/lib/node_modules/mbtiles/node_modules/step/lib/step.js:51:23)
    at next.parallel (/usr/lib/node_modules/mbtiles/node_modules/step/lib/step.js:83:14)
    at Statement.MBTiles._metadata (/usr/lib/node_modules/mbtiles/lib/mbtiles.js:253:25)

It looks like there's no field[] array. Since this error emerged mbpipe doesn't work too as it generates mbtiles with missing tiles.

**Comment by mapsam** [comment]
Hi @shr3k - sorry for the 5 years of silence here. It looks like mbcheck was removed in 0.3.0 https://github.com/mapbox/node-mbtiles/commit/a98037dbdfd19f6cf5a72737cf338654686f734e so going to close this.
